defmodule EmailSucks.Repo.Migrations.AddPhaseZeroSnapshots do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:phase_zero_snapshots, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :account_key, :uuid, null: false
      add :message_ids, {:array, :text}, null: false
      add :status, :text, null: false, default: "pending"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:phase_zero_snapshots, [:account_key],
             name: "phase_zero_snapshots_one_pending_per_account_index",
             where: "(status = 'pending')"
           )
  end

  def down do
    drop_if_exists unique_index(:phase_zero_snapshots, [:account_key],
                     name: "phase_zero_snapshots_one_pending_per_account_index"
                   )

    drop table(:phase_zero_snapshots)
  end
end
