defmodule EmailSucksWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :email_sucks

  # The cookie carries opaque server-side references, never Google credentials.
  @session_options [
    store: :cookie,
    key: "_email_sucks_key",
    signing_salt: "d1yGUIw8",
    encryption_salt: "gmail-session-v1",
    http_only: true,
    secure: Application.compile_env(:email_sucks, :secure_cookies, false),
    max_age: 28_800,
    same_site: "Lax"
  ]

  # socket "/live", Phoenix.LiveView.Socket,
  #   websocket: [connect_info: [session: @session_options]],
  #   longpoll: [connect_info: [session: @session_options]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :email_sucks,
    gzip: not code_reloading?,
    only: EmailSucksWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :email_sucks
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug EmailSucksWeb.Router
end
